name: CI-CD for SQL Scripts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run SQL scripts
        run: |
          docker exec mysql-container mysql -u root -proot -e "CREATE DATABASE test_db;"
          # Agrega tus comandos SQL aquí
