name: CI/CD for SQL Scripts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      # Paso 1: Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v2

      # Paso 2: Esperar hasta que el contenedor de MySQL esté disponible
      - name: Wait for MySQL to be ready
        run: |
          for i in {30..0}; do
            if docker exec mysql mysqladmin ping --silent; then
              break
            fi
            echo 'MySQL is unavailable - sleeping'
            sleep 1
          done
          if [ "$i" = 0 ]; then
            echo 'MySQL did not become available in time' >&2
            exit 1
          fi

      # Paso 3: Crear la base de datos
      - name: Create test database
        run: |
          docker exec mysql mysql -u root -proot -e "CREATE DATABASE test_db;"

      # Paso 4: Ejecutar los scripts SQL
      - name: Run SQL scripts
        run: |
          docker exec -i mysql mysql -u root -proot test_db < Scripts/Tablas_Terminal_Buses.sql
          docker exec -i mysql mysql -u root -proot test_db < Scripts/Ingresos_terminal_buses.sql
          docker exec -i mysql mysql -u root -proot test_db < Scripts/Auditoria/activar_auditoria.sql
          docker exec -i mysql mysql -u root -proot test_db < Scripts/Procedimientos\ Almacenados/Procedure_Terminal_Buses.sql
          docker exec -i mysql mysql -u root -proot test_db < Scripts/Procedimientos\ Almacenados/Triggers_Terminal_Buses.sql
          docker exec -i mysql mysql -u root -proot test_db < Scripts/Procedimientos\ Almacenados/Vistas_Terminal_Buses.sql
          docker exec -i mysql mysql -u root -proot test_db < Scripts/Seguridad/cifrado_datos.sql
          docker exec -i mysql mysql -u root -proot test_db < Scripts/Seguridad/crear_roles.sql
