name: CI-CD for SQL Scripts
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        name: mysql-container
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run SQL scripts
        run: |
          docker exec mysql-container mysql -u root -proot -e "CREATE DATABASE test_db;"
          docker exec -i mysql-container mysql -u root -proot test_db < Scripts/Tablas_Terminal_Buses.sql
          docker exec -i mysql-container mysql -u root -proot test_db < Scripts/Ingresos_terminal_buses.sql
          docker exec -i mysql-container mysql -u root -proot test_db < Scripts/Auditoria/activar_auditoria.sql
          docker exec -i mysql-container mysql -u root -proot test_db < "Scripts/Procedimientos Almacenados/Procedure_Terminal_Buses.sql"
          docker exec -i mysql-container mysql -u root -proot test_db < "Scripts/Procedimientos Almacenados/Triggers_Terminal_Buses.sql"
          docker exec -i mysql-container mysql -u root -proot test_db < "Scripts/Procedimientos Almacenados/Vistas_Terminal_Buses.sql"
          docker exec -i mysql-container mysql -u root -proot test_db < Scripts/Seguridad/cifrado_datos.sql
          docker exec -i mysql-container mysql -u root -proot test_db < Scripts/Seguridad/crear_roles.sql